services:
    openwebui:
        image: ghcr.io/open-webui/open-webui:main
        container_name: openwebui
        restart: unless-stopped
        ports:
          - "3000:8080"
        environment:
          ENABLE_OAUTH_SIGNUP: true
          OAUTH_CLIENT_ID: 'openwebui'
          OAUTH_CLIENT_SECRET_FILE: '/run/secrets/OAUTH_CLIENT_SECRET'
          OPENID_PROVIDER_URL: 'https://auth.trochalakis.com/.well-known/openid-configuration'
          OAUTH_PROVIDER_NAME: 'Authelia'
          OAUTH_SCOPES: 'openid profile email groups'
          OPENID_REDIRECT_URI: 'https://openwebui.trochalakis.net/oauth/oidc/callback'
          OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
        secrets:
          - OAUTH_CLIENT_SECRET
        volumes:
          - /opt/openwebui/data:/app/backend/data
secrets:
  OAUTH_CLIENT_SECRET:
    file: /var/lib/secrets/OAUTH_CLIENT_SECRET
