services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1500
      - PGID=1500
      - TZ=America/Los_Angeles
    volumes:
      - /opt/radarr/data:/config
      - /mnt/media/movies:/movies
      - /syncthing/data:/syncthing
    ports:
      - 7878:7878
    networks:
      - arr-net
    restart: unless-stopped
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1500
      - PGID=1500
      - TZ=America/Los_Angeles
    volumes:
      - /opt/sonarr/data:/config
      - /mnt/media/tv:/tv
      - /syncthing/data:/syncthing
    ports:
      - 8989:8989
    networks:
      - arr-net
    restart: unless-stopped
    
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1500
      - PGID=1500
      - TZ=America/Los_Angeles
    volumes:
      - /opt/lidarr/config:/config
      - /mnt/media/music:/music #optional
      - /syncthing/data:/syncthing
    ports:
      - 8686:8686
    networks:
      - arr-net
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1500
      - PGID=1500
      - TZ=America/Los_Angeles
    volumes:
      - /opt/prowlarr/data:/config
    ports:
      - 9696:9696
    networks:
      - arr-net
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1500
      - PGID=1500
      - TZ=America/Los_Angeles
    volumes:
      - /opt/bazarr/config:/config
      - /mnt/media/movies:/movies #optional
      - /mnt/media/tv:/tv #optional
    ports:
      - 6767:6767
    networks:
      - arr-net
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1500
      - PGID=1500
      - TZ=America/Los_Angeles
    volumes:
      - /opt/overseerr/config:/config
    ports:
      - 5055:5055
    networks:
      - arr-net
    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1500
      - PGID=1500
      - TZ=America/Los_Angeles
    networks:
      - arr-net
    volumes:
      - /syncthing/config:/config
      - /syncthing/data:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    networks:
      - arr-net
    environment:
      - TZ=America/Los_Angeles
      - PUID=1500
      - PGID=1500
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=MyInternalNode
      - auth=false
      - openBrowser=true
      - maxLogSizeMB=10
      - cronPluginUpdate=
    volumes:
      - /opt/tdarr/server:/app/server
      - /opt/tdarr/configs:/app/configs
      - /opt/tdarr/logs:/app/logs
      - /mnt/media:/media
      - /transcode_cache:/temp

networks:
  arr-net:
    name: arr-net
