services:
  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
      - "3000:3000"
#    environment:
      # - HTTP_ALLOWED=true # uncomment this if accessing it over a non-https connection
    volumes:
      - /opt/convertx/data:/app/data
