services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    container_name: caddy
    restart: unless-stopped
    entrypoint: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile", "--envfile", "/run/secrets/CF_API_TOKEN"]
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /etc/caddy/sites:/etc/caddy/sites
      - /etc/caddy/data:/data
      - /etc/caddy/config:/config
    secrets:
      - CF_API_TOKEN
    networks:
      - caddy-net
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    command:
      - 'authelia'
      - '--config=/config/configuration.yml'
      - '--config=/config/config-acl.yml'
      - '--config=/config/config-auth.yml'
      - '--config=/config/config-notifier.yml'
      - '--config=/config/config-oidc.yml'
    volumes:
      - "/etc/authelia:/config"
    environment:
      TZ: 'America/Los_Angeles'
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: '/run/secrets/AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD'
      AUTHELIA_DUO_API_INTEGRATION_KEY_FILE: '/run/secrets/AUTHELIA_DUO_API_INTEGRATION_KEY'
      AUTHELIA_DUO_API_SECRET_KEY_FILE: '/run/secrets/AUTHELIA_DUO_API_SECRET_KEY'
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: '/run/secrets/AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET'
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/run/secrets/AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET'
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: '/run/secrets/AUTHELIA_NOTIFIER_SMTP_PASSWORD'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/run/secrets/AUTHELIA_STORAGE_ENCRYPTION_KEY'
      AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE: '/run/secrets/AUTHELIA_STORAGE_MYSQL_PASSWORD'
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_JKWS_KEY_FILE: '/run/secrets/AUTHELIA_IDENTITY_PROVIDERS_OIDC_JKWS_KEY'
    secrets:
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD
      - AUTHELIA_DUO_API_INTEGRATION_KEY
      - AUTHELIA_DUO_API_SECRET_KEY
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD
      - AUTHELIA_STORAGE_ENCRYPTION_KEY
      - AUTHELIA_STORAGE_MYSQL_PASSWORD
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_JKWS_KEY
    networks:
      - caddy-net

secrets:
  CF_API_TOKEN:
    file: /var/lib/secrets/CF_API_TOKEN.txt
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD:
    file: /var/lib/secrets/AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD
  AUTHELIA_DUO_API_INTEGRATION_KEY:
    file: /var/lib/secrets/AUTHELIA_DUO_API_INTEGRATION_KEY
  AUTHELIA_DUO_API_SECRET_KEY:
    file: /var/lib/secrets/AUTHELIA_DUO_API_SECRET_KEY
  AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET:
    file: /var/lib/secrets/AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET
  AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET:
    file: /var/lib/secrets/AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET
  AUTHELIA_NOTIFIER_SMTP_PASSWORD:
    file: /var/lib/secrets/AUTHELIA_NOTIFIER_SMTP_PASSWORD
  AUTHELIA_STORAGE_ENCRYPTION_KEY:
    file: /var/lib/secrets/AUTHELIA_STORAGE_ENCRYPTION_KEY
  AUTHELIA_STORAGE_MYSQL_PASSWORD:
    file: /var/lib/secrets/AUTHELIA_STORAGE_MYSQL_PASSWORD
  AUTHELIA_IDENTITY_PROVIDERS_OIDC_JKWS_KEY:
    file: /var/lib/secrets/AUTHELIA_IDENTITY_PROVIDERS_OIDC_JKWS_KEY
  
networks:
  caddy-net:
      name: caddy-net
