services:
  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /etc/caddy/sites:/etc/caddy/sites
      - /volumes/caddy/site:/srv
      - /volumes/caddy/data:/data
      - /volumes/caddy/config:/config
    networks:
      - caddy-auth
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    command:
      - 'authelia'
      - '--config=/config/configuration.yml'
      - '--config=/config/config-acl.yml'
      - '--config=/config/config-auth.yml'
      - '--config=/config/config-notifier.yml'
      - '--config=/config/config-oidc.yml'
    volumes:
      - "/etc/authelia:/config" #change this to a shared folder on your system. DO NOT use a "volume"
    networks:
      - caddy-net
    environment:
      - TZ=America/Los_Angeles

networks:
  caddy-net:
      name: caddy-net
